export { config as BetweenYouAndIInstallationConfig } from "./between-you-and-i" 
export { config as BreathIIIInstallationConfig } from "./breath-iii" 
export { config as CouplingInstallationConfig } from "./coupling" 
export { config as DoublingBackInstallationConfig } from "./doubling-back" 
export { config as FaceToFaceInstallationConfig } from "./face-to-face" 
export { config as LeavingInstallationConfig } from "./leaving" 
export { config as MeetingYouHalfwayInstallationConfig } from "./meeting-you-halfway" 
export { config as MultiWorksInstallationConfig } from "./multi-works" 
export { config as SkirtIIIInstallationConfig } from "./skirt-iii" 
export { config as TestInstallationConfig } from "./test" 
export * from "./installation" 
